- 
  hosts: rtp-ls

  tasks: 
      
    - name: Create bgp and traffic
      include_tasks: playbooks/bgp-traffic.yaml

    - name: Create a basic device
      include_tasks: playbooks/device-basic.yaml

    - name: Create a device and Reconnect session
      include_tasks: playbooks/device-create.yaml 
      
    - name: Create an IGMP network
      include_tasks: playbooks/igmp-network.yaml

    - name: Creates a network mesh
      include_tasks: playbooks/stream-mesh.yaml

    - name: Load a predefined XML datamodel
      include_tasks: playbooks/datamodel-loader.yaml

    - name: Deletes an object
      include_tasks: playbooks/delete-object.yaml

    - name: Download log files
      include_tasks: playbooks/download-files.yaml

    - name: Create a few PPPoE device
      include_tasks: playbooks/pppoe-device.yaml
      
    - name: Create bgp and traffic, then modify
      include_tasks: playbooks/bgp-traffic-modify.yaml
      
    - name: Get port configuration
      include_tasks: playbooks/ports-online.yaml
      
    - name: Get stream results
      include_tasks: playbooks/stream-results.yaml
     
    - name: Configure the lab server license and check license
      include_tasks: playbooks/system-config.yaml
      
    - name: Create a dynamic result view
      include_tasks: playbooks/stream-drv.yaml

    - name: Create multiple offline ports
      include_tasks: playbooks/ports-multi.yaml
   
    - name: create ipv6 device
      include_tasks: playbooks/device-create-ipv6-device.yaml

    - name: create ipv4 ipv6 device
      include_tasks: playbooks/device-create-ipv4-ipv6-device.yaml

    - name: create ipv4 single vlan device
      include_tasks: playbooks/device-create-ipv4-single-vlan.yaml

    - name: create ipv6 single vlan device
      include_tasks: playbooks/device-create-ipv6-single-vlan.yaml

    - name: create ipv4 ipv6 single vlan device
      include_tasks: playbooks/device-create-ipv4-ipv6-single-vlan.yaml

    - name: create ipv4 dual vlan device
      include_tasks: playbooks/device-create-ipv4-dual-vlan.yaml

    - name: create ipv6 dual vlan device
      include_tasks: playbooks/device-create-ipv6-dual-vlan.yaml

    - name: create ipv4 ipv6 dual vlan device
      include_tasks: playbooks/device-create-ipv4-ipv6-dual-vlan.yaml 
