- 
  hosts: localhost

  tasks: 

    - name: Create two IGMP device
      include_tasks: playbooks/igmpdevice-example.yaml

    # - name: Create an IGMP mesh network
    #   include_tasks: playbooks/igmpmesh-example.yaml


    # - name: Load a predefined XML datamodel
    #   include_tasks: playbooks/datamodel-loader.yaml


