-
  name: Create session
  stc:
    action: session
    user: ansible
    name: create_device_all
    kill_existing: false
    reset_existing: true


-
  name: Create the base ports
  stc:
    action: create
    objects:
      - project:
          - port:
              location: "//${chassis[0]}/1/1"
              name: Port1

          - port:
              location: "//${chassis[1]}/1/1"
              name: Port2


-
  name: Create 1 emulated devices - port1
  stc:
    action: create
    under: ref:/project
    count: 1
    objects:
    - emulateddevice:
        AffiliatedPort: ref:/port[@name='Port1']
        DeviceCount: 1
        name: "ipv6_device"
        PrimaryIf: ref:./Ipv6If
        TopLevelIf: ref:./Ipv6If
        EthIIIf:
          SourceMac: be:ef:00:00:00:00
        Ipv6If:
          AddrStep: ::1
          Address: 2002::3
          Gateway: 2002::1

-
  name: Create ipv6if under device 1
  stc:
    action: create
    under: ref:/EmulatedDevice[@Name='ipv6_device']
    count: 1
    objects:
    - Ipv6If:
        AddrStep: ::1
        Address: fe80::1
        PrimaryIfSource: ref:/EmulatedDevice[@Name='ipv6_device']
        TopLevelIfSource: ref:/EmulatedDevice[@Name='ipv6_device']

-
  name: config EthIIIf
  stc:
    action: config
    objects: ref:/EmulatedDevice[@Name='ipv6_device']/EthIIIf
    properties:
        stackedonendpoint-Sources: ref:/EmulatedDevice[@Name='ipv6_device']/Ipv6If



-
  name: Create 1 emulated devices - port1
  stc:
    action: create
    under: ref:/project
    count: 1
    objects:
    - emulateddevice:
        AffiliatedPort: ref:/port[@name='Port1']
        DeviceCount: 1
        name: "ipv4_ipv6_device"
        PrimaryIf: ref:./Ipv4If
        TopLevelIf: ref:./Ipv4If
        EthIIIf:
          SourceMac: 00:10:96:00:00:01
        Ipv4If:
          AddrStep: 0.0.0.1
          Address: 192.168.1.2
          Gateway: 192.168.1.1
          StackedOnEndpoint-targets: ref:./EthIIIf
          TopLevelIfSource: ref:/EmulatedDevice[@Name='ipv4_ipv6_device']
          PrimaryIfSource: ref:/EmulatedDevice[@Name='ipv4_ipv6_device']
        Ipv6If:
          AddrStep: ::1
          Address: 2002::1
          Gateway: 2002::2
          StackedOnEndpoint-targets: ref:./EthIIIf
          TopLevelIfSource: ref:/EmulatedDevice[@Name='ipv4_ipv6_device']
          PrimaryIfSource: ref:/EmulatedDevice[@Name='ipv4_ipv6_device']

-
  name: Create ipv6if for device 1
  stc:
    action: create
    under: ref:/EmulatedDevice[@Name='ipv4_ipv6_device']
    count: 1
    objects:
    - Ipv6If:
        AddrStep: ::1
        Address: fe80::1
        PrimaryIfSource: ref:/EmulatedDevice[@Name='ipv4_ipv6_device']
        TopLevelIfSource: ref:/EmulatedDevice[@Name='ipv4_ipv6_device']
        StackedOnEndpoint-targets: ref:/EmulatedDevice[@Name='ipv4_ipv6_device']/EthIIIf


-
  name: Create 1 emulated devices - port1
  stc:
    action: create
    under: ref:/project
    count: 1
    objects:
    - emulateddevice:
        AffiliatedPort: ref:/port[@name='Port1']
        DeviceCount: 1
        name: "ipv4_single_vlan"
        PrimaryIf: ref:./Ipv4If
        TopLevelIf: ref:./Ipv4If
        EthIIIf:
          SourceMac: 00:10:96:00:00:01
        VlanIf:
          VlanId: 100
          StackedOnEndpoint-targets: ref:./EthIIIf
        Ipv4If:
          AddrStep: 0.0.0.1
          Address: 192.168.1.2
          Gateway: 192.168.1.1
          StackedOnEndpoint-targets: ref:./VlanIf
          TopLevelIfSource: ref:/EmulatedDevice[@Name='ipv4_single_vlan']
          PrimaryIfSource: ref:/EmulatedDevice[@Name='ipv4_single_vlan']

-
  name: Create 1 emulated devices - port1
  stc:
    action: create
    under: ref:/project
    count: 1
    objects:
    - emulateddevice:
        AffiliatedPort: ref:/port[@name='Port1']
        DeviceCount: 1
        name: "ipv6_single_vlan"
        PrimaryIf: ref:./Ipv6If
        TopLevelIf: ref:./Ipv6If
        EthIIIf:
          SourceMac: 00:10:96:00:00:01
        VlanIf:
          VlanId: 100
          StackedOnEndpoint-targets: ref:./EthIIIf
        Ipv6If:
          AddrStep: ::1
          Address: 2001::2
          Gateway: 2001::1
          StackedOnEndpoint-targets: ref:./VlanIf
          TopLevelIfSource: ref:/EmulatedDevice[@Name='ipv6_single_vlan']
          PrimaryIfSource: ref:/EmulatedDevice[@Name='ipv6_single_vlan']

-
  name: Create ipv6if under device 1
  stc:
    action: create
    under: ref:/EmulatedDevice[@Name='ipv6_single_vlan']
    count: 1
    objects:
    - Ipv6If:
        AddrStep: ::1
        Address: fe80::2
        PrimaryIfSource: ref:/EmulatedDevice[@Name='ipv6_single_vlan']
        TopLevelIfSource: ref:/EmulatedDevice[@Name='ipv6_single_vlan']
        StackedOnEndpoint-targets: ref:/EmulatedDevice[@Name='ipv6_single_vlan']/VlanIf



-
  name: Create 1 emulated devices - port1
  stc:
    action: create
    under: ref:/project
    count: 1
    objects:
    - emulateddevice:
        AffiliatedPort: ref:/port[@name='Port1']
        DeviceCount: 1
        name: "ipv4_dual_vlan"
        PrimaryIf: ref:./Ipv4If
        TopLevelIf: ref:./Ipv4If
        EthIIIf:
          SourceMac: 00:10:96:00:00:01
        VlanIf:
          VlanId: 100
        Ipv4If:
          AddrStep: 0.0.0.1
          Address: 192.168.1.2
          Gateway: 192.168.1.1
          TopLevelIfSource: ref:/EmulatedDevice[@Name='ipv4_dual_vlan']
          PrimaryIfSource: ref:/EmulatedDevice[@Name='ipv4_dual_vlan']

-
  name: create VlanIf under ipv4_dual_vlan
  stc:
    action: create
    under: ref:/EmulatedDevice[@Name='ipv4_dual_vlan']
    count: 1
    objects:
      - VlanIf:
          VlanId: 200

-
  name: config Ipv4If for ipv4_dual_vlan
  stc:
    action: config
    objects: ref:/EmulatedDevice[@Name='ipv4_dual_vlan']/Ipv4If
    properties:
      StackedOnEndpoint-targets: ref:/EmulatedDevice[@Name='ipv4_dual_vlan']/VlanIf[1]

-
  name: config VlanIf 2 - ipv4_dual_vlan
  stc:
    action: config
    objects: ref:/EmulatedDevice[@Name='ipv4_dual_vlan']/VlanIf[1]
    properties:
      StackedOnEndpoint-targets: ref:/EmulatedDevice[@Name='ipv4_dual_vlan']/VlanIf[0]

-
  name: config VlanIf 1 - ipv4_dual_vlan
  stc:
    action: config
    objects: ref:/EmulatedDevice[@Name='ipv4_dual_vlan']/VlanIf[0]
    properties:
      StackedOnEndpoint-targets: ref:/EmulatedDevice[@Name='ipv4_dual_vlan']/EthIIIf



-
  name: Create 1 emulated devices - port1
  stc:
    action: create
    under: ref:/project
    count: 1
    objects:
    - emulateddevice:
        AffiliatedPort: ref:/port[@name='Port1']
        DeviceCount: 1
        name: "ipv6_dual_vlan"
        PrimaryIf: ref:./Ipv6If
        TopLevelIf: ref:./Ipv6If
        EthIIIf:
          SourceMac: be:ef:00:00:00:00
        VlanIf:
          VlanId: 100
        Ipv6If:
          AddrStep: ::1
          Address: 2001::2
          Gateway: 2001::1

-
  name: Create ipv6if
  stc:
    action: create
    under: ref:/EmulatedDevice[@Name="ipv6_dual_vlan"]
    count: 1
    objects:
      - Ipv6If:
          AddrStep: ::1
          Address: fe80::1
          PrimaryIfSource: ref:/EmulatedDevice[@Name="ipv6_dual_vlan"]
          TopLevelIfSource: ref:/EmulatedDevice[@Name="ipv6_dual_vlan"]

-
  name: create VlanIf under port1
  stc:
    action: create
    under: ref:/EmulatedDevice[@Name="ipv6_dual_vlan"]
    count: 1
    objects:
      - VlanIf:
          VlanId: 200
          StackedOnEndpoint-targets: ref:/EmulatedDevice[@Name="ipv6_dual_vlan"]/VlanIf[0]

-
  name: config ipv6if for port1
  stc:
    action: config
    count: 1
    objects: ref:/EmulatedDevice[@Name="ipv6_dual_vlan"]/Ipv6If[0]
    properties:
      StackedOnEndpoint-targets: ref:/EmulatedDevice[@Name="ipv6_dual_vlan"]/VlanIf[1]

-
  name: config VlanIf for port1
  stc:
    action: config
    count: 1
    objects: ref:/EmulatedDevice[@Name="ipv6_dual_vlan"]/VlanIf[0]
    properties:
      StackedOnEndpoint-targets: ref:/EmulatedDevice[@Name="ipv6_dual_vlan"]/EthIIIf

-
  name: config Ipv6If for port1
  stc:
    action: config
    count: 1
    objects: ref:/EmulatedDevice[@Name="ipv6_dual_vlan"]/Ipv6If[1]
    properties:
      StackedOnEndpoint-targets: ref:/EmulatedDevice[@Name="ipv6_dual_vlan"]/VlanIf[1]



-
  name: Create 1 emulated devices - port1
  stc:
    action: create
    under: ref:/project
    count: 1
    objects:
    - emulateddevice:
        AffiliatedPort: ref:/port[@name='Port1']
        DeviceCount: 1
        name: "ipv4_ipv6_dual_vlan"
        PrimaryIf: ref:./Ipv6If
        TopLevelIf: ref:./Ipv6If
        EthIIIf:
          SourceMac: 00:10:96:00:00:01
        VlanIf:
          VlanId: 100
        Ipv4If:
          AddrStep: 0.0.0.1
          Address: 192.168.1.1
          Gateway: 192.168.1.2
        Ipv6If:
          AddrStep: ::1
          Address: 2002::2
          Gateway: 2002::1

-
  name: create VlanIf under device 1
  stc:
    action: create
    under: ref:/EmulatedDevice[@Name='ipv4_ipv6_dual_vlan']
    count: 1
    objects:
      - VlanIf:
          VlanId: 200

-
  name: Create ipv6if for device 1
  stc:
    action: create
    under: ref:/EmulatedDevice[@Name='ipv4_ipv6_dual_vlan']
    count: 1
    objects:
    - Ipv6If:
        Name: "link_local1"
        AddrStep: ::1
        Address: fe80::1
        PrimaryIfSource: ref:/EmulatedDevice[@Name='ipv4_ipv6_dual_vlan']
        TopLevelIfSource: ref:/EmulatedDevice[@Name='ipv4_ipv6_dual_vlan']

-
  name: config VlanIf for device 1
  stc:
    action: config
    objects: ref:/EmulatedDevice[@Name='ipv4_ipv6_dual_vlan']/VlanIf[1]
    properties:
      StackedOnEndpoint-targets: ref:/EmulatedDevice[@Name='ipv4_ipv6_dual_vlan']/VlanIf[0]

-
  name: config Ipv4If for device 1
  stc:
    action: config
    objects: ref:/EmulatedDevice[@Name='ipv4_ipv6_dual_vlan']/Ipv4If
    properties:
      StackedOnEndpoint-targets: ref:/EmulatedDevice[@Name='ipv4_ipv6_dual_vlan']/VlanIf[1]
      PrimaryIfSource: ref:/EmulatedDevice[@Name='ipv4_ipv6_dual_vlan']
      TopLevelIfSource: ref:/EmulatedDevice[@Name='ipv4_ipv6_dual_vlan']

-
  name: config Ipv6If for device 1
  stc:
    action: config
    objects: ref:/EmulatedDevice[@Name='ipv4_ipv6_dual_vlan']/Ipv6If[0]
    properties:
      StackedOnEndpoint-targets: ref:/EmulatedDevice[@Name='ipv4_ipv6_dual_vlan']/VlanIf[1]

-
  name: config Ipv6If for device 1
  stc:
    action: config
    objects: ref:/EmulatedDevice[@Name='ipv4_ipv6_dual_vlan']/Ipv6If[1]
    properties:
      StackedOnEndpoint-targets: ref:/EmulatedDevice[@Name='ipv4_ipv6_dual_vlan']/VlanIf[1]

-
  name: config VlanIf for device 1
  stc:
    action: config
    objects: ref:/EmulatedDevice[@Name='ipv4_ipv6_dual_vlan']/VlanIf[0]
    properties:
      StackedOnEndpoint-targets: ref:/EmulatedDevice[@Name='ipv4_ipv6_dual_vlan']/EthIIIf


