# -*- coding: utf-8 -*-
# @Author: rjezequel
# @Date:   2019-12-20 09:18:14
# @Last Modified by:   ronanjs
# @Last Modified time: 2020-01-13 15:45:28



- 
  name: Create session
  stc: 
    action: session
    user: ansible
    name: basic_device
    chassis: "{{ hostvars[inventory_hostname].chassis }}"


- 
  name: Create the base ports
  stc: 
    action: create
    objects: 
      - project: 
          - port: 
              location: "//(Offline)/1/1"
              name: Port1



-
  name: create 1 block of 50 devices
  stc: 
    action: create
    under: ref:/project
    objects: 
    - emulateddevice: 
        AffiliatedPort: ref:/port[0]
        DeviceCount: 50
        name: "Device $item"
        tag: "myclient dhcp"
        PrimaryIf: ref:./Ipv4If
        TopLevelIf: ref:./Ipv4If
        EthIIIf: 
          SourceMac: be:ef:00:00:$item:00
        Ipv4If: 
          AddrStep: 0.0.0.2
          Address: 10.0.$item.1
          Gateway: 192.85.1.1
          PrefixLength: 16
          stackedon: ref:./EthIIIf
