-
  name: Create session
  stc:
    action: session
    user: ansible
    name: device_create_ipv6_single_vlan
    chassis: "{{ hostvars[inventory_hostname].chassis }}"


-
  name: Create the base ports
  stc:
    action: create
    objects:
      - project:
          - port:
              location: "//${chassis[0]}/1/1"
              name: Port1

          - port:
              location: "//${chassis[1]}/1/1"
              name: Port2

-
  name: Create 1 emulated devices - port1
  stc:
    action: create
    under: ref:/project
    count: 1
    objects:
    - emulateddevice:
        AffiliatedPort: ref:/port[@name='Port1']
        DeviceCount: 1
        name: "ipv6_single_vlan_1"
        PrimaryIf: ref:./Ipv6If
        TopLevelIf: ref:./Ipv6If
        EthIIIf:
          SourceMac: 00:10:96:00:00:01
        VlanIf:
          VlanId: 100
          StackedOnEndpoint-targets: ref:./EthIIIf
        Ipv6If:
          AddrStep: ::1
          Address: 2001::2
          Gateway: 2001::1
          StackedOnEndpoint-targets: ref:./VlanIf
          TopLevelIfSource: ref:/EmulatedDevice[@Name='ipv6_single_vlan_1']
          PrimaryIfSource: ref:/EmulatedDevice[@Name='ipv6_single_vlan_1']

-
  name: Create ipv6if under device 1
  stc:
    action: create
    under: ref:/EmulatedDevice[@Name='ipv6_single_vlan_1']
    count: 1
    objects:
    - Ipv6If:
        AddrStep: ::1
        Address: fe80::2
        PrimaryIfSource: ref:/EmulatedDevice[@Name='ipv6_single_vlan_1']
        TopLevelIfSource: ref:/EmulatedDevice[@Name='ipv6_single_vlan_1']
        StackedOnEndpoint-targets: ref:/EmulatedDevice[@Name='ipv6_single_vlan_1']/VlanIf



-
  name: create 1 block of 1 devices - ipv6 single vlan
  stc:
    action: perform
    command: DeviceCreate
    properties:
      ParentList:  ref:/project
      CreateCount: 1
      DeviceCount: 1
      Port: ref:/port[@Name='Port2']
      IfStack: Ipv6If VlanIf EthIIIf
      IfCount: '1 1 1'
      name: "ipv6_single_vlan_2"


-
  name: Create ipv6if
  stc:
    action: create
    under: ref:/EmulatedDevice[@Name="ipv6_single_vlan_2"]
    count: 1
    objects:
      - Ipv6If:
          AddrStep: ::1
          Address: fe80::1
          PrimaryIfSource: ref:/EmulatedDevice[@Name="ipv6_single_vlan_2"]
          TopLevelIfSource: ref:/EmulatedDevice[@Name="ipv6_single_vlan_2"]
          StackedOnEndpoint-targets: ref:/EmulatedDevice[@Name="ipv6_single_vlan_2"]/VlanIf

