-
  name: Create session
  stc:
    action: session
    user: ansible
    name: device_create_ipv4_single_vlan
    chassis: "{{ hostvars[inventory_hostname].chassis }}"


-
  name: Create the base ports
  stc:
    action: create
    objects:
      - project:
          - port:
              location: "//${chassis[0]}/1/1"
              name: Port1

          - port:
              location: "//${chassis[1]}/1/1"
              name: Port2

-
  name: Create 1 emulated devices - port1
  stc:
    action: create
    under: ref:/project
    count: 1
    objects:
    - emulateddevice:
        AffiliatedPort: ref:/port[@name='Port1']
        DeviceCount: 1
        name: "ipv4_single_vlan_1"
        PrimaryIf: ref:./Ipv4If
        TopLevelIf: ref:./Ipv4If
        EthIIIf:
          SourceMac: 00:10:96:00:00:01
        VlanIf:
          VlanId: 100
          StackedOnEndpoint-targets: ref:./EthIIIf
        Ipv4If:
          AddrStep: 0.0.0.1
          Address: 192.168.1.2
          Gateway: 192.168.1.1
          StackedOnEndpoint-targets: ref:./VlanIf
          TopLevelIfSource: ref:/EmulatedDevice[@Name='ipv4_single_vlan_1']
          PrimaryIfSource: ref:/EmulatedDevice[@Name='ipv4_single_vlan_1']


-
  name: create 1 block of 1 devices - ipv4 single vlan
  stc:
    action: perform
    command: DeviceCreate
    properties:
      ParentList:  ref:/project
      CreateCount: 1
      DeviceCount: 1
      Port: ref:/port[@Name='Port2']
      IfStack: Ipv4If VlanIf EthIIIf
      IfCount: '1 1 1'
      name: "ipv4_single_vlan_2"
