

- 
  name: Create session
  stc: 
    action: session
    user: ansible
    name: device_tag
    chassis: "{{ hostvars[inventory_hostname].chassis }}"


- 
  name: Create the base ports
  stc: 
    action: create
    objects: 
      - project: 
          - port: 
              location: "//${chassis[0]}/1/1"
              name: Port1

          - port: 
              location: "//${chassis[1]}/1/1"
              name: Port2


# - case1： if tag is not exiting in stc, create the tag first,
  #        then set the created tag handle to usertag-targets of emulateddevice for create
  #        if tag can be found in stc by ref:/tags/tag[name=custom-tag-name],
  #        get the handles of the tag, set the tag handles to usertag-targets of emulateddevice for create 
  
  # name: create an emulate device with a custom tag
  # stc:
    # action: create
    # under: /Project
    # count: 1
    # objects:
    # - tags:
        # - tag:
            # name: "bgptag"
        # - tag:
            # name: "custom-tag-name" 
    # - EmulatedDevice:
        # name: "BGPRouter"
        # usertag-targets: "ref:/tags/tag[name=bgptag] ref:/tags/tag[name=custom-tag-name]"
        # AffiliatedPort: ref:/port[@name='Port1']

-
  name: create an emulate device with a custom tag
  stc:
    action: create
    under: /Project
    count: 1
    objects:
    - EmulatedDevice:
        name: "BGPRouter"
        tag: "bgptag custom-tag-name"
        AffiliatedPort: ref:/port[@name='Port1']



# - case2： if tag is not exiting in stc, create the tag first,
  #        then after perform "DeviceCreate" command, 
  #        set the created tag handle to usertag-targets of emulateddevice created by perform
  #        if tag can be found in stc by ref:/tags/tag[name=mytag-$item],
  #        get the handles of the tag,  after perform "DeviceCreate" command, 
  #        set the tag handles to usertag-targets of emulateddevice created by perform
-
  name: create 20 block of 50 devices
  stc: 
    action: perform
    command: DeviceCreate
    properties: 
      ParentList:  ref:/project
      CreateCount: 20
      DeviceCount: 50
      Port: ref:/port[@Name='Port1']
      IfStack: Ipv4If PppIf PppoeIf EthIIIf
      IfCount: '1 1 1 1'
      name: "dev-$item"
      tag: "mytag-$item"



# - case3： if tag is not exiting in stc, create the tag first,
  #        then set the created tag handle to usertag-targets of emulateddevice for config
  #        if tag can be found in stc by ref:/tags/tag[name=bgptag],
  #        get the handles of the tag, set the tag handles to usertag-targets of emulateddevice for config
-
  # name: Configure each device IP address
  # stc: 
    # action: config
    # count: 20
    # objects: /EmulatedDevice[@Name='dev-$item']
    # properties:
        # Ipv4If: 
          # AddrStep: 0.0.0.1
          # usertag-targets: ref:/tags/tag[name=custom-tag-$item]
-
  name: Configure each device IP address
  stc: 
    action: config
    count: 20
    objects: /EmulatedDevice[@Name='dev-$item']
    properties:
        Ipv4If: 
          AddrStep: 0.0.0.1
          tag: "custom-tag-$item"



# - case4： if tag is not exiting in stc, cannot found the device with this tag, 
  #        if tag can be found in stc by ref:/tags/tag[name=custom-tag-$item],
  #        get the handles of the tag, set the tag handles to usertag-targets of emulateddevice 
  #        for xpath parsing to find the emulateddevices
-
  # name: Configure each device IP address
  # stc: 
    # action: config
    # count: 20
    # objects: /EmulatedDevice[@usertag-targets=ref:/tags/tag[name=custom-tag-$item]]
    # properties:
        # Ipv4If: 
          # AddrStep: 0.0.0.2
          # Address: 10.0.$item.1

-
  name: Configure each device IP address
  stc: 
    action: config
    count: 20
    objects: /EmulatedDevice[@tag='custom-tag-$item']
    properties:
        Ipv4If: 
          AddrStep: 0.0.0.2
          Address: 10.0.$item.1



# - case5： if tag is not exiting in stc, cannot found the device with this tag, 
  #        if tag can be found in stc by ref:/tags/tag[name=custom-tag-name],
  #        get the handles of the tag, set the tag handles to usertag-targets of emulateddevice
  #        for xpath parsing to find the emulateddevices
  
  # name: create bgp on this device with the tag 'custom-tag-name'
  # stc:
    # action: create
    # under: /EmulatedDevice[@usertag-targets=ref:/tags/tag[name=custom-tag-name]]
    # count: 1
    # objects:
    # - BgpRouterConfig:
        # AsNum: 1111
        # DutAsNum: 2222
        # name: "BGPRouter1"
-
  name: create bgp on this device with the tag 'custom-tag-name'
  stc:
    action: create
    under: /EmulatedDevice[@tag*='custom-tag-name']
    count: 1
    objects:
    - BgpRouterConfig:
        AsNum: 1111
        DutAsNum: 2222
        name: "BGPRouter1"

-
  name: Take the ports online
  stc: 
    action: perform
    command: AttachPorts
    properties:
      RevokeOwner: true
      PortList: ref:/port



-
  name: Take the ports offline
  stc: 
    action: perform
    command: DetachPortsCommand
    properties:
      PortList: ref:/port
