-
  name: Create session
  stc:
    action: session
    user: ansible
    name: device_create_perform_all
    chassis: "{{ hostvars[inventory_hostname].chassis }}"


-
  name: Create the base ports
  stc:
    action: create
    objects:
      - project:
          - port:
              location: "//${chassis[0]}/1/1"
              name: Port1

          - port:
              location: "//${chassis[1]}/1/1"
              name: Port2



-
  name: create 1 block of 1 devices
  stc:
    action: perform
    command: DeviceCreate
    properties:
      ParentList:  ref:/project
      CreateCount: 1
      DeviceCount: 1
      Port: ref:/port[@Name='Port2']
      IfStack: Ipv6If EthIIIf
      IfCount: '1 1'
      name: "ipv6_device"

-
  name: Create ipv6if
  stc:
    action: create
    under: ref:/EmulatedDevice[@Name="ipv6_device"]
    count: 1
    objects:
      - Ipv6If:
          AddrStep: ::1
          Address: fe80::1
          PrimaryIfSource: ref:/EmulatedDevice[@Name="ipv6_device"]
          TopLevelIfSource: ref:/EmulatedDevice[@Name="ipv6_device"]
          StackedOnEndpoint-targets: ref:/EmulatedDevice[@Name="ipv6_device"]/EthIIIf


-
  name: create 1 block of 1 devices
  stc:
    action: perform
    command: DeviceCreate
    properties:
      ParentList:  ref:/project
      CreateCount: 1
      DeviceCount: 1
      Port: ref:/port[@Name='Port2']
      IfStack: Ipv6If Ipv4If EthIIIf
      IfCount: '1 1 1'
      name: "ipv4_ipv6_device"

-
  name: Config ipv4if address
  stc:
    action: config
    objects: ref:/EmulatedDevice[@Name='ipv4_ipv6_device']/Ipv4If
    properties:
      Address: 192.168.1.1
      Gateway: 192.168.1.2
      TopLevelIfSource: ref:/EmulatedDevice[@Name="ipv4_ipv6_device"]

-
  name: Config ipv6if address
  stc:
    action: config
    objects: ref:/EmulatedDevice[@Name='ipv4_ipv6_device']/Ipv6If
    properties:
      Address: 2001::1
      Gateway: 2001::2
      StackedOnEndpoint-targets: ref:/EmulatedDevice[@Name="ipv4_ipv6_device"]/EthIIIf

-
  name: Create ipv6if
  stc:
    action: create
    under: ref:/EmulatedDevice[@Name="ipv4_ipv6_device"]
    count: 1
    objects:
      - Ipv6If:
          AddrStep: ::1
          Address: fe80::1
          PrimaryIfSource: ref:/EmulatedDevice[@Name="ipv4_ipv6_device"]
          TopLevelIfSource: ref:/EmulatedDevice[@Name="ipv4_ipv6_device"]
          StackedOnEndpoint-targets: ref:/EmulatedDevice[@Name="ipv4_ipv6_device"]/EthIIIf



-
  name: create 1 block of 1 devices - ipv4 single vlan
  stc:
    action: perform
    command: DeviceCreate
    properties:
      ParentList:  ref:/project
      CreateCount: 1
      DeviceCount: 1
      Port: ref:/port[@Name='Port2']
      IfStack: Ipv4If VlanIf EthIIIf
      IfCount: '1 1 1'
      name: "ipv4_single_vlan"


-
  name: create 1 block of 1 devices - ipv4 dual vlan
  stc:
    action: perform
    command: DeviceCreate
    properties:
      ParentList:  ref:/project
      CreateCount: 1
      DeviceCount: 1
      Port: ref:/port[@Name='Port2']
      IfStack: Ipv4If VlanIf VlanIf EthIIIf
      IfCount: '1 1 1 1'
      name: "ipv4_dual_vlan"


-
  name: create 1 block of 1 devices - ipv6 single vlan
  stc:
    action: perform
    command: DeviceCreate
    properties:
      ParentList:  ref:/project
      CreateCount: 1
      DeviceCount: 1
      Port: ref:/port[@Name='Port2']
      IfStack: Ipv6If VlanIf EthIIIf
      IfCount: '1 1 1'
      name: "ipv6_single_vlan"


-
  name: Create ipv6if
  stc:
    action: create
    under: ref:/EmulatedDevice[@Name="ipv6_single_vlan"]
    count: 1
    objects:
      - Ipv6If:
          AddrStep: ::1
          Address: fe80::1
          PrimaryIfSource: ref:/EmulatedDevice[@Name="ipv6_single_vlan"]
          TopLevelIfSource: ref:/EmulatedDevice[@Name="ipv6_single_vlan"]
          StackedOnEndpoint-targets: ref:/EmulatedDevice[@Name="ipv6_single_vlan"]/VlanIf


-
  name: create 1 block of 1 devices - ipv6 dual vlan
  stc:
    action: perform
    command: DeviceCreate
    properties:
      ParentList:  ref:/project
      CreateCount: 1
      DeviceCount: 1
      Port: ref:/port[@Name='Port2']
      IfStack: Ipv6If VlanIf VlanIf EthIIIf
      IfCount: '1 1 1 1'
      name: "ipv6_dual_vlan"


-
  name: Create ipv6if
  stc:
    action: create
    under: ref:/EmulatedDevice[@Name="ipv6_dual_vlan"]
    count: 1
    objects:
      - Ipv6If:
          AddrStep: ::1
          Address: fe80::3
          PrimaryIfSource: ref:/EmulatedDevice[@Name="ipv6_dual_vlan"]
          TopLevelIfSource: ref:/EmulatedDevice[@Name="ipv6_dual_vlan"]
          StackedOnEndpoint-targets: ref:/EmulatedDevice[@Name="ipv6_dual_vlan"]/VlanIf[0]


-
  name: create 1 block of 1 devices - ipv4 ipv6 single vlan
  stc:
    action: perform
    command: DeviceCreate
    properties:
      ParentList:  ref:/project
      CreateCount: 1
      DeviceCount: 1
      Port: ref:/port[@Name='Port2']
      IfStack: Ipv6If Ipv4If VlanIf EthIIIf
      IfCount: '1 1 1 1'
      name: "ipv4_ipv6_single_vlan"


-
  name: config ipv6if
  stc:
    action: config
    objects: ref:/EmulatedDevice[@Name='ipv4_ipv6_single_vlan']/Ipv4If
    properties:
      Address: 192.168.2.2
      Gateway: 192.168.2.1
      StackedOnEndpoint-targets: ref:/EmulatedDevice[@Name="ipv4_ipv6_single_vlan"]/VlanIf


-
  name: config ipv4if
  stc:
    action: config
    objects: ref:/EmulatedDevice[@Name='ipv4_ipv6_single_vlan']/Ipv4If
    properties:
      Address: 192.168.2.2
      Gateway: 192.168.2.1
      TopLevelIfSource: ref:/EmulatedDevice[@Name="ipv4_ipv6_single_vlan"]


-
  name: Create ipv6if
  stc:
    action: create
    under: ref:/EmulatedDevice[@Name="ipv4_ipv6_single_vlan"]
    count: 1
    objects:
      - Ipv6If:
          AddrStep: ::1
          Address: fe80::4
          PrimaryIfSource: ref:/EmulatedDevice[@Name="ipv4_ipv6_single_vlan"]
          TopLevelIfSource: ref:/EmulatedDevice[@Name="ipv4_ipv6_single_vlan"]
          StackedOnEndpoint-targets: ref:/EmulatedDevice[@Name="ipv4_ipv6_single_vlan"]/VlanIf


-
  name: create 1 block of 1 devices - ipv4 ipv6 dual vlan
  stc:
    action: perform
    command: DeviceCreate
    properties:
      ParentList:  ref:/project
      CreateCount: 1
      DeviceCount: 1
      Port: ref:/port[@Name='Port2']
      IfStack: Ipv6If Ipv4If VlanIf VlanIf EthIIIf
      IfCount: '1 1 1 1 1'
      name: "ipv4_ipv6_dual_vlan"

-
  name: config ipv4if
  stc:
    action: config
    objects: ref:/EmulatedDevice[@Name='ipv4_ipv6_dual_vlan']/Ipv4If
    properties:
      TopLevelIfSource: ref:/EmulatedDevice[@Name="ipv4_ipv6_dual_vlan"]

-
  name: config ipv6if
  stc:
    action: config
    objects: ref:/EmulatedDevice[@Name='ipv4_ipv6_dual_vlan']/Ipv6If
    properties:
      StackedOnEndpoint-targets: ref:/EmulatedDevice[@Name="ipv4_ipv6_dual_vlan"]/VlanIf[0]

-
  name: Create ipv6if
  stc:
    action: create
    under: ref:/EmulatedDevice[@Name="ipv4_ipv6_dual_vlan"]
    count: 1
    objects:
      - Ipv6If:
          AddrStep: ::1
          Address: fe80::5
          PrimaryIfSource: ref:/EmulatedDevice[@Name="ipv4_ipv6_dual_vlan"]
          TopLevelIfSource: ref:/EmulatedDevice[@Name="ipv4_ipv6_dual_vlan"]
          StackedOnEndpoint-targets: ref:/EmulatedDevice[@Name="ipv4_ipv6_dual_vlan"]/VlanIf[0]


