# -*- coding: utf-8 -*-
# @Author: rjezequel
# @Date:   2019-12-20 09:18:14
# @Last Modified by:   ronanjs
# @Last Modified time: 2020-01-13 15:45:28



- 
  name: Create session
  stc: 
    action: session
    user: ansible
    name: create_device
    kill_existing: false
    reset_existing: true


- 
  name: Create one base port
  stc: 
    action: create
    objects: 
      - project: 
          - port: 
              location: "//(Offline)/1/1"
              name: Port1
          - port: 
              location: "//(Offline)/1/1"
              name: Port2


-
  name: create 2 block of 50 devices
  stc: 
    action: perform
    command: DeviceCreate
    properties: 
      ParentList:  ref:/project
      CreateCount: 2
      DeviceCount: 50
      Port: ref:/port[@Name='Port1']
      IfStack: Ipv4If PppIf PppoeIf EthIIIf
      IfCount: '1 1 1 1'
      name: "client-$item"
      tag: 'client dhcp'


-
  name: create 2 block of 50 devices
  stc: 
    action: perform
    command: DeviceCreate
    properties: 
      ParentList:  ref:/project
      CreateCount: 2
      DeviceCount: 50
      Port: ref:/port[@Name='Port2']
      IfStack: Ipv4If PppIf PppoeIf EthIIIf
      IfCount: '1 1 1 1'
      name: "server-$item"
      tag: 'server dhcp'


- 
  name: Reconnect to the session
  stc: 
    action: session
    user: ansible
    name: create_device
    kill_existing: false
    reset_existing: false


-
  name: Configure each device IP address
  stc: 
    action: config
    count: 2
    objects: /EmulatedDevice[@Name='client-$item']
    properties:
        Ipv4If: 
          AddrStep: 0.0.0.1
          Address: 10.0.$item.1

