
- 
  name: Create session
  stc: 
    action: session
    user: ansible
    name: device_tag
    chassis: "{{ hostvars[inventory_hostname].chassis }}"


- 
  name: Create the base ports
  stc: 
    action: create
    objects: 
      - project: 
          - port: 
              location: "//${chassis[0]}/1/1"
              name: Port1

          - port: 
              location: "//${chassis[1]}/1/1"
              name: Port2


- name: create multiple emulate devices with one custom tag
  stc:
    action: create
    under: /Project
    count: 3
    objects:
    - EmulatedDevice:
        name: "BGPRouter-$item"
        tag: "routertag"
        AffiliatedPort: ref:/port[@name='Port1']

-
  name: Configure multiple device IP by editing its tags
  stc: 
    action: config
    objects: /EmulatedDevice[@tag='routertag']
    properties:
        tag: "~routertag &bgptag"
        
-
  name: create an emulate device with a custom tag
  stc:
    action: create
    under: /Project
    count: 1
    objects:
    - EmulatedDevice:
        name: "BGPRouter"
        tag: "atag"
        AffiliatedPort: ref:/port[@name='Port1']

-
  name: create an emulate device with custom tags
  stc:
    action: create
    under: /Project
    count: 1
    objects:
    - EmulatedDevice:
        name: "BGPRouter$item"
        tag: "bgptag mytag"
        AffiliatedPort: ref:/port[@name='Port1']


-
  name: Configure each device IP by removing its tag 
  stc: 
    action: config
    objects: /EmulatedDevice[@tag='mytag bgptag']
    properties:
        tag: "~bgptag &atag"
          
-
  name: Configure each device by its tag
  stc: 
    action: config
    objects: /EmulatedDevice[@tag*='atag mytag']
    properties:
        tag: "~mytag"

-
  name: Configure each device by removing its tag
  stc: 
    action: config
    objects: /EmulatedDevice[@tag='atag']
    properties:
        tag: "~atag"
          

     

- name: perform command on multiple devices by tag
  stc: 
    action: perform
    command: BgpAdvertiseRouteCommand
    properties: 
        routelist: /EmulatedDevice[tag="bgptag"]
        PrefixFilter: 4


-
  name: Take the ports online
  stc: 
    action: perform
    command: AttachPorts
    properties:
      RevokeOwner: true
      PortList: ref:/port



-
  name: Take the ports offline
  stc: 
    action: perform
    command: DetachPortsCommand
    properties:
      PortList: ref:/port
