- 
  name: Create session
  register: result
  stc: 
    action: new_session
    user: ansible
    name: igmp-decice

- 
  name: Create the base ports
  register: result
  stc: 
    action: create
    objects: 
      - project: 
          - port: 
              location: "//(Offline)/1/1"
              name: Port1

          - port: 
              location: "//(Offline)/2/1"
              name: Port2

-
  name: Create 2 blocks of emulated devices
  register: result
  stc: 
    action: create
    under: ref:/project
    count: 2
    objects: 
    - emulateddevice: 
        AffiliatedPort: ref:/port[name=Port1]
        DeviceCount: 10
        name: "IGMP Device $item"
        PrimaryIf: ref:./Ipv4If
        TopLevelIf: ref:./Ipv4If
        EthIIIf: 
          SourceMac: be:ef:00:00:$item:00
        Ipv4If: 
          AddrStep: 0.0.0.2
          Address: 10.0.$item.1
          Gateway: 192.85.1.1
          PrefixLength: 16
          stackedon: ref:./EthIIIf


- 
  name: Configure the associated PPPoeIF client device
  stc: 
    count: 2
    action: config
    parent: ref:/EmulatedDevice[Name=IGMP Device $item]
    properties:
      PppIf:
        stackedon: ref:../PppoeIf
        name: PPP interface
      PppoeIf:
        stackedon: ref:../EthIIIf
        IfCountPerLowerIf: 1
        name: PPPoE interface
      Ipv4If:
        stackedon: ref:../PppIf
      PppoeServerBlockConfig:
        AcName: mintaka
        Authentication: CHAP_MD5
        ConnectRate: 1000
        TotalClients: 10
        PppoeServerIpv4PeerPool: 
          Ipv4PeerPoolAddr: 10.0.0.1
          NetworkCount: 100000
          PrefixLength: 24

- 
  name: Configure the traffic generator
  stc: 
    action: create
    under: ref:/port[name=Port1]
    objects: 
    - StreamBlock: 
        name: Stream1
        EnableStreamOnlyGeneration: true
        SrcBinding-targets: ref:/EmulatedDevice[Name=IGMP Device 1]/Ipv4If
        DstBinding-targets: ref:/EmulatedDevice[Name=IGMP Device 0]/Ipv4If
        AffiliationStreamBlockLoadProfile: 
          Load: 100

- 
  name: Configure the traffic analyser
  stc: 
    action: config
    parent: ref:/project
    properties:
      analyzerpreloadprofile:
        AffiliationAnalyzerPreloadStreamBlock-targets: ref:/port[name=Port1]/StreamBlock


- 
  name: Start the traffic
  stc: 
    action: perform
    command: GeneratorStart
    properties: 
      GeneratorList: ref:/project 
