- 
  name: Create session
  register: result
  stc: 
    action: new_session
    user: ansible
    name: igmp-mesh

- 
  name: Create the base ports
  register: result
  stc: 
    action: create
    objects: 
      - project: 
          - port: 
              location: "//(Offline)/1/1"
              name: Port1
              VxlanPortConfig:
                UdpDstPort: 88

          - port: 
              location: "//(Offline)/2/1"
              name: Port2

-
  name: create 18 device blocks with name
  register: result
  stc: 
    action: perform
    command: DeviceCreate
    properties: 
      ParentList:  ref:/project
      CreateCount: 18
      DeviceCount: 1
      Port: ref:/port[Name=Port1]
      IfStack: Ipv4If PppIf PppoeIf EthIIIf
      IfCount: '1 1 1 1'
      name: "IGMP Client $item"

- 
  name: Configure the associated PPPoeIF client device
  stc: 
    count: 18
    action: config
    parent: ref:/EmulatedDevice[Name=IGMP Client $item]
    properties:
      PppIf:
        stackedon: ref:../PppoeIf
        name: PPP interface
      PppoeIf:
        stackedon: ref:../EthIIIf
        IfCountPerLowerIf: 1
        name: PPPoE interface
      Ipv4If:
        stackedon: ref:../PppIf
      PppoeServerBlockConfig:
        AcName: mintaka
        Authentication: CHAP_MD5
        ConnectRate: 1000
        TotalClients: 10
        PppoeServerIpv4PeerPool: 
          Ipv4PeerPoolAddr: 10.0.0.1
          NetworkCount: 100000
          PrefixLength: 24


- 
  name: Configure the traffic generator
  stc: 
    count: 18
    action: create
    under: ref:/port[name=Port1]
    objects: 
    - StreamBlock: 
        name: stream $item
        EnableStreamOnlyGeneration: true
        SrcBinding-targets: ref:/EmulatedDevice[Name=IGMP Client $item]/Ipv4If
        DstBinding-targets: ref:/EmulatedDevice[Name=IGMP Client 0]/Ipv4If
        AffiliationStreamBlockLoadProfile: 
          Load: 100

- 
  name: Configure the traffic analyser
  stc: 
    count: 18
    action: config
    parent: ref:/project
    properties:
      analyzerpreloadprofile:
        AffiliationAnalyzerPreloadStreamBlock-targets: ref:/port[name=Port1]/StreamBlock


