################################################################################################################
# Playbook Name : multiple-chassis-ports-config.yaml
# Description : In STC Ansible, Need to pass the multiple chassis ports in the inventory file for 
#               port performance scale test
#
# Ticket in Salesforce: [STC-I-266](https://ideas.spirent.com/ideas/STC-I-266)
#                       [STC-I-266] **Multiple Chassis or Single chassis connection with multiple Ports**
#
# Owner : Madhuri Katta
# Created : 16/07/2020
#################################################################################################################



############Test0##############

# Inventory settings

#rtp11-ls ansible_host=10.66.240.73 chassis="10.109.120.47 10.109.114.0"
#rtp1-ls ansible_host=10.66.240.73 chassis="10.109.120.47 10.109.114.0" ports="//10.109.120.47/1/1 //10.109.114.0/1/1" names="port11 port22"
#rtp2-ls ansible_host=10.66.240.77 chassis="10.108.8.20" ports="//10.108.8.20/2/1-6,7,8" names="port[1:8]"
#rtp3-ls ansible_host=10.66.240.77 chassis="10.108.8.20" ports="//10.108.8.20/9/1 //10.108.8.20/9/2" names="Port1 Port2"

- name: Create a session with predefined chassis, ports and names in the inventory
  stc: 
    action: session
    user: ansible
    name: multi-port-test0
    chassis: "{{ hostvars[inventory_hostname].chassis }}"
    ports: "{{ hostvars[inventory_hostname].ports }}"
    names: "{{ hostvars[inventory_hostname].names }}"
    

############Test1##############
- name: Create a session with single chassis,slot and multiple ports -- creates 8 ports
  stc: 
    action: session
    user: ansible
    name: multi-port-test1
    chassis: "{{ hostvars[inventory_hostname].chassis }}"
    ports: "//${chassis[0]}/2/1-5,6,8 //${chassis[0]}/2/7"
    names: "port[1:7] qmport[8:8]"

-
  name: Create the base ports
  stc:
    action: create
    count: 8
    objects:
      - project:
          - port:
              location: ${ports[item]}
              name: ${names[item]}

-
  name: Get the actual port configuration
  register: result
  stc:
    action: get
    objects: ref:/port

- 
  debug:
    var: result
    
############Test2##############
    
- name: Create a session with single chassis and multiple slots/ports -- creates 6 ports
  stc: 
    action: session
    user: ansible
    name: multi-port-test2
    chassis: "{{ hostvars[inventory_hostname].chassis }}"
    ports: "//${chassis[0]}/2/1-3,4,5 //${chassis[0]}/9/1"
    names: "port[1:5] [6:6]myport"

-
  name: Create the base ports
  stc:
    action: create
    count: 6
    objects:
      - project:
          - port:
              location: ${ports[item]}
              name: ${names[item]}

-
  name: Get the actual port configuration
  register: result
  stc:
    action: get
    objects: ref:/port

- 
  debug:
    var: result
    
############Test2##############
- name: Create a session with multiple chassis and multiple slots/ports -- creates 6 ports
  stc: 
    action: session
    user: ansible
    name: multi-port-test3
    chassis: "{{ hostvars[inventory_hostname].chassis }}"
    ports: "//${chassis[0]}/2/1-3,4,5 //${chassis[1]}/1/1"
    names: "port[1:5] [6:6]myport"
    
-
  name: Create the base ports
  stc:
    action: create
    count: 6
    objects:
      - project:
          - port:
              location: ${ports[item]}
              name: ${names[item]}

-
  name: Get the actual port configuration
  register: result
  stc:
    action: get
    objects: ref:/port

- 
  debug:
    var: result