- 
  name: Create session
  stc: 
    action: session
    user: ansible
    name: ports_online
    chassis: "{{ hostvars[inventory_hostname].chassis }}"

-
  name: Create the base ports
  stc:
    action: create
    objects:
      - project:
          - port:
              location: "//${chassis[0]}/1/1"
              name: Port1
          - port:
              location: "//${chassis[1]}/1/1"
              name: Port2


-
  name: Get the actual port configuration
  register: result
  stc:
    action: get
    objects: ref:/port

- 
  debug:
    var: result

