# -*- coding: utf-8 -*-
# @Author: rjezequel
# @Date:   2019-12-20 09:18:14
# @Last Modified by:   ronanjs
# @Last Modified time: 2020-01-13 15:45:28

- debug:
    var: "{{ hostvars[inventory_hostname] }}"


- 
  name: Create session
  stc: 
    action: session
    user: ansible
    name: pppoe_device
    chassis: "{{ hostvars[inventory_hostname].chassis }}"


- 
  name: Create the base ports
  stc: 
    action: create
    objects: 
      - project: 
          - port: 
              location: "//${chassis[0]}/1/1"
              name: Port1
              PppoxPortConfig:
                EmulationType: Client
                SessionOutstanding: 1000
                DisconnectRate: 1000
                ConnectRate: 1000

          - port: 
              location: "//${chassis[1]}/1/1"
              name: Port2
              PppoxPortConfig:
                EmulationType: Server
                SessionOutstanding: 1000
                DisconnectRate: 1000
                ConnectRate: 1000


# ----------------- Client config ------------------

-
  name: create the client device block
  stc: 
    action: perform
    command: DeviceCreate
    properties: 
      ParentList:  ref:/project
      CreateCount: 1
      DeviceCount: 300
      Port: ref:/port[Name=Port1]
      IfStack: Ipv4If PppIf PppoeIf EthIIIf
      IfCount: '1 1 1 1'
      name: "PPPoE Client"

- 
  name: Configure the client device block
  stc: 
    action: config
    object: ref:/EmulatedDevice[Name=PPPoE Client]
    properties:
      PppoeClientBlockConfig:
        ConnectRate: 100
        DisconnectRate: 1000
        Authentication: CHAP_MD5


# ----------------- Server config ------------------

-
  name: create the server device block
  stc: 
    action: perform
    command: DeviceCreate
    properties: 
      ParentList:  ref:/project
      CreateCount: 1
      DeviceCount: 1000
      Port: ref:/port[Name=Port2]
      IfStack: Ipv4If PppIf PppoeIf EthIIIf
      IfCount: '1 1 1 1'
      name: "PPPoE Server"

-
  name: configure the server device block
  stc: 
    action: config
    object: ref:/EmulatedDevice[Name=PPPoE Server]
    properties:
      PppoeServerBlockConfig:
        AcName: mintaka
        Authentication: CHAP_MD5
        ConnectRate: 1000
        TotalClients: 1000
        PppoeServerIpv4PeerPool: 
          Ipv4PeerPoolAddr: 10.0.0.1
          NetworkCount: 100000
          PrefixLength: 24


-
  name: subscribe to server results
  stc: 
    action: perform
    command: SubscribeResultsView
    properties: 
      ExecuteSynchronous: true
      TemplateUri: "/Result Views/Access Protocols/PPPoX Results.xml"

# ----------------- take ports online ------------------

-
  name: Take the ports online
  stc: 
    action: perform
    command: AttachPorts
    properties:
      RevokeOwner: true
      PortList: ref:/port[*]

# ----------------- then bind the devices ------------------

-
  name: Start the server ...
  stc: 
    action: perform
    command: PppoxConnect
    properties: 
      BlockList: ref:/EmulatedDevice[Name=PPPoE Server]/PppoeServerBlockConfig


-
  name: Wait for the server to be ready
  stc: 
    action: wait
    object: ref:/EmulatedDevice[Name=PPPoE Server]/PppoeServerBlockConfig
    until: BlockState=CONNECTING
    

-
  name: And then bind the clients...
  stc: 
    action: perform
    command: PppoxConnect
    properties: 
      BlockList: ref:/EmulatedDevice[Name=PPPoE Client]/PppoeClientBlockConfig


-
  name: Wait for the clients to be bound
  stc: 
    action: wait
    object: ref:/EmulatedDevice[Name=PPPoE Client]/PppoeClientBlockConfig
    until: BlockState=CONNECTED



- 
  name: Get the binding results
  register: results
  stc:
    action: get
    object: ref:/EmulatedDevice[Name=PPPoE Server]/PppoeServerBlockConfig/PppoeServerBlockResults

- 
  debug:
    var: result

