# -*- coding: utf-8 -*-
# @Author: rjezequel
# @Date:   2019-12-20 09:18:14
# @Last Modified by:   ronanjs
# @Last Modified time: 2020-01-13 15:45:28

- 
  name: Create session
  stc: 
    action: new_session
    user: ansible
    name: basic-device

- 
  name: Create the base ports
  stc: 
    action: create
    objects: 
      - project: 
          - port: 
              location: "//(Offline)/1/1"
              name: Port1

          - port: 
              location: "//(Offline)/2/1"
              name: Port2

-
  name: create the client device block
  stc: 
    action: perform
    command: DeviceCreate
    properties: 
      ParentList:  ref:/project
      CreateCount: 1
      DeviceCount: 100
      Port: ref:/port[Name=Port1]
      IfStack: Ipv4If PppIf PppoeIf EthIIIf
      IfCount: '1 1 1 1'
      name: "PPPoE Client"

- 
  name: Configure the client device block
  stc: 
    action: config
    object: ref:/EmulatedDevice[Name=PPPoE Client]
    properties:
      PppoeClientBlockConfig:
        ConnectRate: 1000
        DisconnectRate: 1000
        Authentication: CHAP_MD5



-
  name: create the server device block
  stc: 
    action: perform
    command: DeviceCreate
    properties: 
      ParentList:  ref:/project
      CreateCount: 1
      DeviceCount: 1
      Port: ref:/port[Name=Port2]
      IfStack: Ipv4If PppIf PppoeIf EthIIIf
      IfCount: '1 1 1 1'
      name: "PPPoE Server"

-
  name: configure the server device block
  stc: 
    action: config
    object: ref:/EmulatedDevice[Name=PPPoE Server]
    properties:
      PppoeServerBlockConfig:
        AcName: mintaka
        Authentication: CHAP_MD5
        ConnectRate: 1000
        TotalClients: 10
        PppoeServerIpv4PeerPool: 
          Ipv4PeerPoolAddr: 10.0.0.1
          NetworkCount: 100000
          PrefixLength: 24

-
  name: Start the server ...
  stc: 
    action: perform
    command: PppoxConnect
    properties: 
      BlockList: ref:/EmulatedDevice[Name=PPPoE Server]/PppoeServerBlockConfig

-
  name: And then bind the clients...
  stc: 
    action: perform
    command: PppoxConnect
    properties: 
      BlockList: ref:/EmulatedDevice[Name=PPPoE Client]/PppoeClientBlockConfig
