

# - 
  # name: Create session
  # stc: 
    # action: session
    # user: ansible
    # name: session_create
    # chassis: "{{ hostvars[inventory_hostname].chassis }}"

- 
  name: Create session
  stc: 
    action: create
    objects:
     - session:
            user: ansible
            name: session_create
            chassis: "{{ hostvars[inventory_hostname].chassis }}"


- 
  name: Create the base ports
  stc: 
    action: create
    objects: 
      - project: 
          - port: 
              location: "//${chassis[0]}/1/1"
              name: Port1

          - port: 
              location: "//${chassis[1]}/1/1"
              name: Port2

-
  name: create 20 block of 50 devices
  stc: 
    action: perform
    command: DeviceCreate
    properties: 
      ParentList:  ref:/project
      CreateCount: 20
      DeviceCount: 50
      Port: ref:/port[@Name='Port1']
      IfStack: Ipv4If PppIf PppoeIf EthIIIf
      IfCount: '1 1 1 1'
      name: "dev-$item"


-
  name: Configure each device IP address
  stc: 
    action: config
    count: 20
    objects: /EmulatedDevice[@Name='dev-$item']
    properties:
        Ipv4If: 
          AddrStep: 0.0.0.1
          Address: 10.0.$item.1


-
  name: Take the ports online
  stc: 
    action: perform
    command: AttachPorts
    properties:
      RevokeOwner: true
      PortList: ref:/port



-
  name: Take the ports offline
  stc: 
    action: perform
    command: DetachPortsCommand
    properties:
      PortList: ref:/port
